#!/usr/bin/env bash

# ============================================================================
# Alembic Migration Commands Cheatsheet
# ============================================================================

echo "📚 Alembic Migrations Guide for Book API"
echo "=========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}## SETUP${NC}"
echo "# Initialize Alembic (already done in this project)"
echo "alembic init alembic"
echo ""

echo -e "${BLUE}## CREATE MIGRATIONS${NC}"
echo "# Create a new migration manually"
echo "alembic revision -m 'description of changes'"
echo ""
echo "# Create a migration with autogenerate (detects model changes)"
echo "alembic revision --autogenerate -m 'add new column'"
echo ""

echo -e "${BLUE}## RUN MIGRATIONS${NC}"
echo "# Upgrade to the latest version"
echo -e "${GREEN}alembic upgrade head${NC}"
echo ""
echo "# Upgrade by specific number of revisions"
echo "alembic upgrade +1  # Upgrade by 1 revision"
echo "alembic upgrade +2  # Upgrade by 2 revisions"
echo ""
echo "# Upgrade to a specific revision"
echo "alembic upgrade 001"
echo ""

echo -e "${BLUE}## ROLLBACK MIGRATIONS${NC}"
echo "# Downgrade by one revision"
echo -e "${YELLOW}alembic downgrade -1${NC}"
echo ""
echo "# Downgrade to a specific revision"
echo "alembic downgrade 001"
echo ""
echo "# Downgrade all the way"
echo "alembic downgrade base"
echo ""

echo -e "${BLUE}## VIEW MIGRATION STATUS${NC}"
echo "# Show current revision"
echo "alembic current"
echo ""
echo "# Show migration history"
echo "alembic history"
echo ""
echo "# Show detailed migration history"
echo "alembic history --verbose"
echo ""

echo -e "${BLUE}## DATABASE SWITCHING${NC}"
echo "# For SQLite (default in alembic.ini)"
echo "alembic upgrade head"
echo ""
echo "# For PostgreSQL - set environment variable"
echo "export DATABASE_URL='postgresql://user:password@localhost/bookstore'"
echo "alembic upgrade head"
echo ""

echo -e "${BLUE}## COMMON WORKFLOWS${NC}"
echo ""
echo -e "${GREEN}1. Initial setup (fresh database):${NC}"
echo "   alembic upgrade head"
echo ""
echo -e "${GREEN}2. After modifying models:${NC}"
echo "   alembic revision --autogenerate -m 'describe changes'"
echo "   # Review the generated migration file"
echo "   alembic upgrade head"
echo ""
echo -e "${GREEN}3. Rolling back a bad migration:${NC}"
echo "   alembic downgrade -1"
echo "   # Fix the migration file"
echo "   alembic upgrade head"
echo ""

echo -e "${BLUE}## TESTING MIGRATIONS${NC}"
echo "# Test upgrade and downgrade cycle"
echo "alembic upgrade head"
echo "alembic downgrade base"
echo "alembic upgrade head"
echo ""

echo -e "${YELLOW}## IMPORTANT NOTES${NC}"
echo "✓ Always review autogenerated migrations before applying"
echo "✓ Test migrations on a copy of production data"
echo "✓ Keep migrations in version control"
echo "✓ Never modify applied migrations"
echo "✓ Always create a new migration for schema changes"
echo ""

echo "For more info: https://alembic.sqlalchemy.org/"
